### ISSUE TITLE
RedJade

### ISSUE THREAD

**Issue by keithharvey** [redjade/misc#1]
Hey, I am part of an organization called RedJade, which is an employee-owned business but that wasn't always the case. I was curious about your own inception for the name or if we might discuss purchasing your GitHub profile for our organization. Our current name incorporates our old parent company and I'd like to divorce the company from that storied history. Thanks for your time and I apologize for contacting you in this way.

daniel@redjade.net

**Comment by redjade** [comment]
It is English translation of my first name.
